http_port 3128
auth_param basic program /usr/lib/squid/basic_ncsa_auth /etc/squid/passwords
auth_param basic realm ChaiQualification
acl authenticated proxy_auth REQUIRED
http_access allow authenticated
http_access deny all
access_log stdio:/var/log/squid/access.log
cache deny all
visible_hostname chai-squid-auth
